
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-4"> 
          <img src="https://rrsign.com.br/imagens/diagrama/diagrama-assinatura-digital-e-eletronica-da-rrdocs.png" class="img-fluid">
        </div>
    </div>
</div>

<div  style="background-color: #ec8433; ">
<div class="container mt-4 py-4">
    <div class="row">
        <div class="col-md-6"> 
        <form action="/lead" method="post">
            <div class="form-group">
                
                <input type="text" class="form-control" name="nome"  placeholder="Nome">

            </div>
        
            <div class="form-group">
                
                <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Email">

            </div>
                <input type="hidden" class="form-control" name="id_lp" value="1">
           
               <button type="submit" class="btn btn-primary" style="width:100% !important;"> Enviar</button>
            </form>
        </div>
        <div class="col-md-6">
            <h2 style="color: white"> A nossa empresa está comprometida com um mundo mais sustentável, venha fazer parte desta idéia!</h2>
       </div>
    </div>
</div>
</div>

